In [1]:
#Numpy for ds
import numpy as np

array1 = np.array([0,1,2,3,4,5])


In [2]:
#Let's create an array using variables that already exists
notes = [16, 17, 14 , 17, 19, 13]

ar_notes = np.array(notes, dtype=float)


In [4]:
#2-D array

total_notes = np.array(([0,1,2,3,4,5], notes))
total_notes 

array([[ 0,  1,  2,  3,  4,  5],
       [16, 17, 14, 17, 19, 13]])

In [6]:
#Some operations
a = np.array([1,2,3])
b = np.array([0,1,1])

b.dot(a)

5

In [8]:
#In 2-D

a = np.array(([5,1],[3,2]))
b = np.array(([2,3],[0,5]))

a.dot(b)

array([[10, 20],
       [ 6, 19]])

In [10]:
#A better way:
a @ b

array([[10, 20],
       [ 6, 19]])

In [11]:
np.matmul(a,b) #<- Another way

array([[10, 20],
       [ 6, 19]])

In [12]:
#To find the determinant
np.linalg.det(a)

6.999999999999999

In [15]:
#Eigen values and eigen vectors
vals, vecs= np.linalg.eig(a)
print(vals)
print(vecs)

[5.79128785 1.20871215]
[[ 0.78419037 -0.25504011]
 [ 0.62052031  0.96693047]]
